### PR TITLE
Fix mails fetching

### LINKED ISSUE #20: Receiving "Inbox is empty" message
I am trying to get an email from yopmail by unsing yogo but I always receive the message "Inbox is empty". 

yogo.exe inbox show <mail> 1

I tried the other commands as well with the same result. I used it a month ago and everything works as expected. Maybe yopmail has something changed?

### PR DESCRIPTION
**Pull request by antham**
Fix #20

### CODE REVIEW

File: inbox/util.go [hunk 1]
```diff
@@ -28,33 +27,34 @@ var buildReader = func(method string, URL string, headers map[string]string, bod
...
 
-var fetchURL = func(URL string) (*goquery.Document, error) {
-	doc, err := goquery.NewDocument(URL)
+func fetchURL(URL string) (*goquery.Document, error) {
+	resp, err := http.Get(URL)
+	if err != nil {
+		return nil, err
+	}
 
+	doc, err := goquery.NewDocumentFromResponse(resp)
```
Comment (golangcibot) [inline inbox/util.go]: SA1019: goquery.NewDocumentFromResponse is deprecated: Use goquery.NewDocumentFromReader with the response's body.  (from `staticcheck`)
